# docker-compose.yml
---
version: '3.1'
services:
  db:
    image: pgvector/pgvector:0.8.0-pg16
    restart: always
    environment:
      POSTGRES_USER: abc
      POSTGRES_PASSWORD: def
      POSTGRES_DB: mydb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
