---
services:
  bot:
    build: .
    restart: always
    volumes:
      - ./log:/app/log
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mydb
    networks:
      - coordinate
    depends_on:
      - db

  db:
    image: pgvector/pgvector:0.8.0-pg16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mydb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./scripts/db:/docker-entrypoint-initdb.d
    networks:
      - coordinate

networks:
  coordinate:
    driver: bridge
